### ISSUE TITLE
Can't add toggl token

### ISSUE THREAD

**Issue by sojusnik** [josehbez/gp-tracking#6]
Hey!

The new toggl plugin seems not to be working. When adding a token, then the following appears:

    ~$ gp-tracking --toggl-token 34jf827162hdasf...

usage: gp-tracking [-h] --clockify-token CLOCKIFY\_TOKEN
gp-tracking: error: the following arguments are required: --clockify-token

or

    ~$ gp-tracking --plugin toggl

usage: gp-tracking [-h] --clockify-token CLOCKIFY\_TOKEN
gp-tracking: error: the following arguments are required: --clockify-token

**Comment by sojusnik** [comment]
Seems not to help:

```
~$ gp-tracking --clockify-token token-x-only-for-skip-process
{"message":"Full authentication is required to access this resource","code":1000}
```

BTW, I don't have a clockify account, only toggl.

**Comment by josehbez** [comment]
I added new patch, try: 
```
Uninstall 
sh -c "$(curl -fsSL https://raw.githubusercontent.com/josehbez/gp-tracking/master/uninstall.sh)"

And install
sh -c "$(curl -fsSL https://raw.githubusercontent.com/josehbez/gp-tracking/master/install.sh)"

```

**Comment by sojusnik** [comment]
Thanks, works now!

BTW, Pomodoros under 2 minutes aren't captured by Toggl. Is this a limitation of Toggl or your plugin? At the beginning I thought that your plugin isn't working, because for testing purposes my Pomodoros were shorter than 2 minutes. Would love to see, that Pomodoros under 2 minutes were captured too.

Did you think about getting in touch with the maintainer of [gnome-pomodoro](https://github.com/codito/gnome-pomodoro), to advertise your plugin there? I think that a lot of people will find it quite useful.

Also, it should help to add "toggl" to the tag cloud of your project's GitHub page, see:
![grafik](https://user-images.githubusercontent.com/1245718/98523095-c8c7fe00-2275-11eb-8b51-a7affe162330.png)

**Comment by josehbez** [comment]
Thanks your feedback.

- I'll contact with manteiner gnome-poomodo, 
- gp-tracking, only track above 2 minutes,  I'm work the new settings param for configure mnimal traceability
